const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#0A84FF",
    background: "#F2F2F7",
    foreground: "#0a0a0a",
    card: "#FFFFFF",
    cardForeground: "#0a0a0a",
    primary: "#0A84FF",
    primaryForeground: "#ffffff",
    secondary: "#E5E5EA",
    secondaryForeground: "#1a1a1a",
    muted: "#E5E5EA",
    mutedForeground: "#6C6C70",
    accent: "#FF9F0A",
    accentForeground: "#ffffff",
    destructive: "#FF453A",
    destructiveForeground: "#ffffff",
    success: "#32D74B",
    successForeground: "#ffffff",
    warning: "#FF9F0A",
    warningForeground: "#ffffff",
    border: "#C6C6C8",
    input: "#E5E5EA",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#0A84FF",
    background: "#0C0C0E",
    foreground: "#FFFFFF",
    card: "#1C1C1F",
    cardForeground: "#FFFFFF",
    primary: "#0A84FF",
    primaryForeground: "#ffffff",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#AEAEB2",
    accent: "#FF9F0A",
    accentForeground: "#ffffff",
    destructive: "#FF453A",
    destructiveForeground: "#ffffff",
    success: "#32D74B",
    successForeground: "#ffffff",
    warning: "#FF9F0A",
    warningForeground: "#ffffff",
    border: "#38383A",
    input: "#2C2C2E",
  },
  radius: 12,
};

export default colors;
